<a href="https://colab.research.google.com/github/BrennoPereira/CursoDeExtens-oPythonPandas2023-1/blob/main/Primeiro_Exemplo_em_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Primeiro exemplo de manipulação de dados usando Python Pandas **

Autor: Brenno Pereira 

Data: 06 de fevereiro de 2023

In [ ]:
#importando biblioteca pandas no Python
import pandas as pd

combustiveis_df = pd.read_excel("ca-2021-02.xlsx")

In [ ]:
# Usar print para ver o datafarme ! (Mostra tudo)

print(combustiveis_df)

       Regiao - Sigla Estado - Sigla  Municipio  \
0                  NE             AL  ARAPIRACA
1                  NE             AL  ARAPIRACA
2                  NE             AL  ARAPIRACA
3                  NE             AL  ARAPIRACA
4                  NE             AL  ARAPIRACA
...               ...            ...        ...
168404             NE             BA     JEQUIE
168405             SE             MG  ITUIUTABA
168406             SE             MG  ITUIUTABA
168407             SE             MG  ITUIUTABA
168408             SE             MG  ITUIUTABA

                                           Revenda      CNPJ da Revenda  \
0                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
1                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
2                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
3                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
4                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
...                                            ...                  ...
168404  COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA   28.629.089/0001-79
168405           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38
168406           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38
168407           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38
168408           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38

                                      Nome da Rua Numero Rua Complemento  \
0                                  RODOVIA AL 220        105       KM 68
1                                  RODOVIA AL 220        105       KM 68
2                                  RODOVIA AL 220        105       KM 68
3                                  RODOVIA AL 220        105       KM 68
4                                  RODOVIA AL 220        105       KM 68
...                                           ...        ...         ...
168404                  AVENIDA T LOT JD TROPICAL         53         NaN
168405  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN
168406  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN
168407  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN
168408  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN

             Bairro        Cep             Produto Data da Coleta  \
0       CANAFISTULA  57302-605            GASOLINA     2021-11-01
1       CANAFISTULA  57302-605              ETANOL     2021-11-01
2       CANAFISTULA  57302-605              DIESEL     2021-11-01
3       CANAFISTULA  57302-605  GASOLINA ADITIVADA     2021-11-01
4       CANAFISTULA  57302-605          DIESEL S10     2021-11-01
...             ...        ...                 ...            ...
168404     TROPICAL  45209-130              ETANOL     2021-12-31
168405     ALVORADA  38307-113            GASOLINA     2021-12-31
168406     ALVORADA  38307-113              ETANOL     2021-12-31
168407     ALVORADA  38307-113          DIESEL S10     2021-12-31
168408     ALVORADA  38307-113  GASOLINA ADITIVADA     2021-12-31

        Valor de Venda  Valor de Compra Unidade de Medida       Bandeira
0                6.799              NaN        R$ / litro  VIBRA ENERGIA
1                5.299              NaN        R$ / litro  VIBRA ENERGIA
2                5.549              NaN        R$ / litro  VIBRA ENERGIA
3                6.899              NaN        R$ / litro  VIBRA ENERGIA
4                5.649              NaN        R$ / litro  VIBRA ENERGIA
...                ...              ...               ...            ...
168404           5.859              NaN        R$ / litro     PETROSERRA
168405           6.580              NaN        R$ / litro         BRANCA
168406           4.740              NaN        R$ / litro         BRANCA
168407           5.448              NaN        R$ / litro         BRANCA
168408           6.580              NaN        R$ / litro         BRANCA

[168409 rows x 16 columns]

In [ ]:
# Mostrar as primeiras 5 linhas 
# Display e print quase mesma coisa, porém o display mostra mais organizado.
# função .head filtra o numeros de linhas

display(combustiveis_df.head())

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA,2021-11-01,6.799,NaN,R$ / litro,VIBRA ENERGIA
1,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,ETANOL,2021-11-01,5.299,NaN,R$ / litro,VIBRA ENERGIA
2,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL,2021-11-01,5.549,NaN,R$ / litro,VIBRA ENERGIA
3,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA ADITIVADA,2021-11-01,6.899,NaN,R$ / litro,VIBRA ENERGIA
4,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL S10,2021-11-01,5.649,NaN,R$ / litro,VIBRA ENERGIA

In [ ]:
# Exibir apenas as 15 primeiras linhas.

display(combustiveis_df.head(15))

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA,2021-11-01,6.799,NaN,R$ / litro,VIBRA ENERGIA
1,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,ETANOL,2021-11-01,5.299,NaN,R$ / litro,VIBRA ENERGIA
2,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL,2021-11-01,5.549,NaN,R$ / litro,VIBRA ENERGIA
3,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA ADITIVADA,2021-11-01,6.899,NaN,R$ / litro,VIBRA ENERGIA
4,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL S10,2021-11-01,5.649,NaN,R$ / litro,VIBRA ENERGIA
5,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,GASOLINA,2021-11-01,7.198,NaN,R$ / litro,VIBRA ENERGIA
6,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,ETANOL,2021-11-01,5.982,NaN,R$ / litro,VIBRA ENERGIA
7,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,DIESEL,2021-11-01,5.974,NaN,R$ / litro,VIBRA ENERGIA
8,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,GASOLINA ADITIVADA,2021-11-01,7.208,NaN,R$ / litro,VIBRA ENERGIA
9,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,DIESEL S10,2021-11-01,5.983,NaN,R$ / litro,VIBRA ENERGIA
10,NE,AL,DELMIRO GOUVEIA,AUTO POSTO DA PEDRA LTDA,05.518.639/0001-87,RUA FLORIANO PEIXOTO,281,NaN,CENTRO,57480-000,GASOLINA,2021-11-01,7.197,NaN,R$ / litro,BRANCA
11,NE,AL,DELMIRO GOUVEIA,AUTO POSTO DA PEDRA LTDA,05.518.639/0001-87,RUA FLORIANO PEIXOTO,281,NaN,CENTRO,57480-000,ETANOL,2021-11-01,5.987,NaN,R$ / litro,BRANCA
12,NE,AL,DELMIRO GOUVEIA,AUTO POSTO DA PEDRA LTDA,05.518.639/0001-87,RUA FLORIANO PEIXOTO,281,NaN,CENTRO,57480-000,DIESEL,2021-11-01,5.978,NaN,R$ / litro,BRANCA
13,NE,AL,DELMIRO GOUVEIA,AUTO POSTO DA PEDRA LTDA,05.518.639/0001-87,RUA FLORIANO PEIXOTO,281,NaN,CENTRO,57480-000,DIESEL S10,2021-11-01,5.989,NaN,R$ / litro,BRANCA
14,NE,AL,DELMIRO GOUVEIA,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,04.431.113/0001-00,AVENIDA CAXANGA,126,NaN,PEDRA VELHA,57480-000,GASOLINA,2021-11-01,7.175,NaN,R$ / litro,BRANCA

In [ ]:
# Comandos Dataframe.shape linhas e colunas e 
# Dataframe.describe() mostra estatisticas "mais básicas" que a gente precisa
display(combustiveis_df.shape[0])
print(combustiveis_df.describe())

168409

       Valor de Venda  Valor de Compra
count   168409.000000              0.0
mean         6.005184              NaN
std          0.794541              NaN
min          2.849000              NaN
25%          5.339000              NaN
50%          5.859000              NaN
75%          6.699000              NaN
max          8.990000              NaN

In [ ]:
# Info: Quais são colunas e que tipo de dados cada um tem... *importante*
display(combustiveis_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168409 entries, 0 to 168408
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Regiao - Sigla     168409 non-null  object
 1   Estado - Sigla     168409 non-null  object
 2   Municipio          168409 non-null  object
 3   Revenda            168409 non-null  object
 4   CNPJ da Revenda    168409 non-null  object
 5   Nome da Rua        168409 non-null  object
 6   Numero Rua         168353 non-null  object
 7   Complemento        35057 non-null   object
 8   Bairro             168043 non-null  object
 9   Cep                168409 non-null  object
 10  Produto            168409 non-null  object
 11  Data da Coleta     168409 non-null  datetime64[ns]
 12  Valor de Venda     168409 non-null  float64
 13  Valor de Compra    0 non-null       float64
 14  Unidade de Medida  168409 non-null  object
 15  Bandeira           168409 non-null  object
dtypes: datetime64[ns](1), float64(2), object(13)
memory usage: 20.6+ MB

None

In [ ]:
# Filtrar apenas uma coluna e as 250 primeiras linhas
print(combustiveis_df.head(250)["Data da Coleta"])

0     2021-11-01
1     2021-11-01
2     2021-11-01
3     2021-11-01
4     2021-11-01
         ...
245   2021-11-01
246   2021-11-01
247   2021-11-01
248   2021-11-01
249   2021-11-01
Name: Data da Coleta, Length: 250, dtype: datetime64[ns]

In [ ]:
# Filtrar apenas uma coluna e as 50 ultimas linhas, Usando o .tail 
print(combustiveis_df.tail(50)["Revenda"])

168359                            AUTO POSTO GUARATIBA LTDA
168360                            AUTO POSTO GUARATIBA LTDA
168361                       AUTO POSTO ALMEIDA BRITO LTDA.
168362                       AUTO POSTO ALMEIDA BRITO LTDA.
168363                       AUTO POSTO ALMEIDA BRITO LTDA.
168364                                  POSTO 5.5. LIMITADA
168365                                  POSTO 5.5. LIMITADA
168366                                  POSTO 5.5. LIMITADA
168367              AEROPOSTO COMERCIO DE COMBUSTIVEIS LTDA
168368              AEROPOSTO COMERCIO DE COMBUSTIVEIS LTDA
168369              AEROPOSTO COMERCIO DE COMBUSTIVEIS LTDA
168370              AEROPOSTO COMERCIO DE COMBUSTIVEIS LTDA
168371    CAPIXABA COMERCIO DE PRODUTOS AUTOMOTIVOS LTDA...
168372    CAPIXABA COMERCIO DE PRODUTOS AUTOMOTIVOS LTDA...
168373    CAPIXABA COMERCIO DE PRODUTOS AUTOMOTIVOS LTDA...
168374    CAPIXABA COMERCIO DE PRODUTOS AUTOMOTIVOS LTDA...
168375                   CENTRO AUTOMOTIVO ELEFANTINHO LTDA
168376                   CENTRO AUTOMOTIVO ELEFANTINHO LTDA
168377                   CENTRO AUTOMOTIVO ELEFANTINHO LTDA
168378                   CENTRO AUTOMOTIVO ELEFANTINHO LTDA
168379                   CENTRO AUTOMOTIVO ELEFANTINHO LTDA
168380    POSTO DE COMBUSTIVEIS - BEIRA VALAO DE CAMPOS ...
168381    POSTO DE COMBUSTIVEIS - BEIRA VALAO DE CAMPOS ...
168382    POSTO DE COMBUSTIVEIS - BEIRA VALAO DE CAMPOS ...
168383    POSTO DE COMBUSTIVEIS - BEIRA VALAO DE CAMPOS ...
168384                              AUTO POSTO RAIDEN LTDA.
168385                              AUTO POSTO RAIDEN LTDA.
168386                              AUTO POSTO RAIDEN LTDA.
168387                              AUTO POSTO RAIDEN LTDA.
168388    M W COMERCIO DE COMBUSTIVEIS SERVICOS E ALIMEN...
168389    M W COMERCIO DE COMBUSTIVEIS SERVICOS E ALIMEN...
168390    M W COMERCIO DE COMBUSTIVEIS SERVICOS E ALIMEN...
168391    M W COMERCIO DE COMBUSTIVEIS SERVICOS E ALIMEN...
168392                             AUTO POSTO KM BAURU LTDA
168393                             AUTO POSTO KM BAURU LTDA
168394        COOPERCITRUS COOPERATIVA DE PRODUTORES RURAIS
168395        COOPERCITRUS COOPERATIVA DE PRODUTORES RURAIS
168396        COOPERCITRUS COOPERATIVA DE PRODUTORES RURAIS
168397        COOPERCITRUS COOPERATIVA DE PRODUTORES RURAIS
168398        COOPERCITRUS COOPERATIVA DE PRODUTORES RURAIS
168399    VICMAR COMERCIO DE COMBUSTIVEIS E LUBRIFICANTE...
168400    VICMAR COMERCIO DE COMBUSTIVEIS E LUBRIFICANTE...
168401    VICMAR COMERCIO DE COMBUSTIVEIS E LUBRIFICANTE...
168402           COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA
168403           COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA
168404           COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA
168405                    ABC DISTRIBUICAO DE PETROLEO LTDA
168406                    ABC DISTRIBUICAO DE PETROLEO LTDA
168407                    ABC DISTRIBUICAO DE PETROLEO LTDA
168408                    ABC DISTRIBUICAO DE PETROLEO LTDA
Name: Revenda, dtype: object

In [ ]:
# Criando novo dataframe apenas com algumas colunas que eu quero;
simples_df = combustiveis_df[['Revenda','Municipio','Valor de Venda','Produto']]
display(simples_df.tail())

,Revenda,Municipio,Valor de Venda,Produto
168404,COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA,JEQUIE,5.859,ETANOL
168405,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,6.580,GASOLINA
168406,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,4.740,ETANOL
168407,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,5.448,DIESEL S10
168408,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,6.580,GASOLINA ADITIVADA

In [ ]:
# Exibir a 4a linha  ---> só as imformações que quero.
display(simples_df.loc[4][["Revenda",'Valor de Venda']])

Revenda           POSTO ARAPIRACA LTDA
Valor de Venda                   5.649
Name: 4, dtype: object

In [ ]:
# Exibir da 10a linha até a 20a linha. 
display(simples_df.loc[10:20])
#display(simples_df.loc[10:20][['Revenda','Valor de Venda','Produto']])

,Revenda,Municipio,Valor de Venda,Produto
10,AUTO POSTO DA PEDRA LTDA,DELMIRO GOUVEIA,7.197,GASOLINA
11,AUTO POSTO DA PEDRA LTDA,DELMIRO GOUVEIA,5.987,ETANOL
12,AUTO POSTO DA PEDRA LTDA,DELMIRO GOUVEIA,5.978,DIESEL
13,AUTO POSTO DA PEDRA LTDA,DELMIRO GOUVEIA,5.989,DIESEL S10
14,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,DELMIRO GOUVEIA,7.175,GASOLINA
15,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,DELMIRO GOUVEIA,5.930,ETANOL
16,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,DELMIRO GOUVEIA,5.955,DIESEL
17,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,DELMIRO GOUVEIA,7.175,GASOLINA ADITIVADA
18,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,DELMIRO GOUVEIA,5.980,DIESEL S10
19,MARCOS ANTONIO DA SILVA CABRAL,ITACOATIARA,6.990,GASOLINA
20,MARCOS ANTONIO DA SILVA CABRAL,ITACOATIARA,5.890,ETANOL

In [ ]:
# Criar um dataframe gas_df contendo 
# apenas as 4 colunas (Revenda, Municipio, Produto, Valor de Venda)
# somente com combustível sendo GASOLINA e exibir na tela

gas_df = simples_df.loc[simples_df['Produto'] == 'GASOLINA']
display(gas_df)
print(gas_df['Valor de Venda'].max())

,Revenda,Municipio,Valor de Venda,Produto
0,POSTO ARAPIRACA LTDA,ARAPIRACA,6.799,GASOLINA
5,AUTO POSTO FREITAS & MAIA LTDA,DELMIRO GOUVEIA,7.198,GASOLINA
10,AUTO POSTO DA PEDRA LTDA,DELMIRO GOUVEIA,7.197,GASOLINA
14,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,DELMIRO GOUVEIA,7.175,GASOLINA
19,MARCOS ANTONIO DA SILVA CABRAL,ITACOATIARA,6.990,GASOLINA
...,...,...,...,...
168392,AUTO POSTO KM BAURU LTDA,BAURU,6.199,GASOLINA
168394,COOPERCITRUS COOPERATIVA DE PRODUTORES RURAIS,ITUIUTABA,6.899,GASOLINA
168399,VICMAR COMERCIO DE COMBUSTIVEIS E LUBRIFICANTE...,CAMPOS DOS GOYTACAZES,7.090,GASOLINA
168403,COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA,JEQUIE,6.799,GASOLINA
168405,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,6.580,GASOLINA

7.999

In [ ]:
# Exibir qual é o posto e munícipio da gasolina mais cara do brasil e outro produto.
display(combustiveis_df[['Valor de Venda','Revenda','Municipio','Produto']].max() )
display(gas_df[['Revenda','Municipio','Valor de Venda']].max())

Valor de Venda                         8.99
Revenda           ZV POSTO DE SERVIÇO LTDA.
Municipio                           XANXERE
Produto                                 GNV
dtype: object

Revenda           ZV POSTO DE SERVIÇO LTDA.
Municipio                           XANXERE
Valor de Venda                        7.999
dtype: object

In [ ]:
# Dataframe.loc[] com múltiplas condições para filtragem. 
# Quais são os preços, postos que vendem ETANOL na minha cidade (SÃO PAULO)
etanol_saopaulo_df = simples_df.loc[(simples_df['Produto'] == 'ETANOL')  & (simples_df['Municipio'] == 'SAO PAULO')]
#etanol_indaiatuba_df = simples_df.loc[(simples_df['Produto'] == 'ETANOL') & (simples_df['Municipio'] == 'INDAIATUBA')] 
display(etanol_saopaulo_df)
etanol_saopaulo_df.sort_values(by='Valor de Venda', inplace=True)

,Revenda,Municipio,Valor de Venda,Produto
1602,ELITE POSTO DE SERVICOS LTDA,SAO PAULO,5.199,ETANOL
6417,AUTO POSTO RENOVACAO LTDA,SAO PAULO,4.999,ETANOL
6420,CENTRO AUTOMOTIVO MADRI LTDA.,SAO PAULO,5.199,ETANOL
6424,ADECAR COMÉRCIO E SERVIÇOS AUTOMOTIVOS LTDA.,SAO PAULO,5.399,ETANOL
6428,AUTO POSTO SENTINELA LTDA,SAO PAULO,4.849,ETANOL
...,...,...,...,...
164933,CENTRO AUTOMOTIVO SINERGIA LTDA,SAO PAULO,4.899,ETANOL
165238,COMERCIO DE COMBUSTIVEIS BRAGANCA EIRELI,SAO PAULO,5.099,ETANOL
165536,CENTRO AUTOMOTIVO ACC RADIAL LTDA,SAO PAULO,4.899,ETANOL
165925,COMPANHIA BRASILEIRA DE DISTRIBUICAO,SAO PAULO,4.799,ETANOL
166123,RADIAL LESTE COMERCIO VAREJISTA DE COMBUSTIVEI...,SAO PAULO,4.779,ETANOL

/usr/local/lib/python3.8/dist-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

POR algum motivo estava dando errado, copiei o codigo do professor para ver o que estava errado. acho que resolveu porem nao sei o que era ainda

In [ ]:
# Qual a média de preços dos combustíveis GASOLINA e GASOLINA ADITIVADA do Bairro MOOCA/tatuape em SÃO PAULO?
display(combustiveis_df.loc[(combustiveis_df['Bairro'] == 'VILA SABRINA') & (combustiveis_df['Municipio'] == 'SAO PAULO') & ((combustiveis_df['Produto'] == 'GASOLINA') | (combustiveis_df['Produto'] == 'GASOLINA ADITIVADA')), ['Valor de Venda', 'Produto']].max())

Valor de Venda                 6.799
Produto           GASOLINA ADITIVADA
dtype: object


1.   **max():** Preço mais alto
2.   **min():** Preço minimo
3.   **mean():** Media

In [ ]:
# Curiosidade
#display(combustiveis_df.loc[(combustiveis_df ['Bairro'] == 'VILA SABRINA') & (combustiveis_df['Municipio'] == 'SAO PAULO' ) | ((combustiveis_df['Produto']) =='GASOLINA') )])
display(combustiveis_df.loc[(combustiveis_df ['Bairro'] == 'VILA SABRINA') & (combustiveis_df['Municipio'] == 'SAO PAULO' ) & ((combustiveis_df['Produto']) =='GASOLINA')].max())

Regiao - Sigla                                     SE
Estado - Sigla                                     SP
Municipio                                   SAO PAULO
Revenda              POSTO DE SERVICOS DIESELMAC LTDA
CNPJ da Revenda                    62.392.261/0001-51
Nome da Rua                          RUA ALONSO PERES
Numero Rua                                        640
Complemento                                      None
Bairro                                   VILA SABRINA
Cep                                         02161-020
Produto                                      GASOLINA
Data da Coleta                    2021-12-09 00:00:00
Valor de Venda                                  6.599
Valor de Compra                                   NaN
Unidade de Medida                          R$ / litro
Bandeira                                       RAIZEN
dtype: object

In [86]:
# Qual a média de preços dos combustíveis GASOLINA e GASOLINA ADITIVADA do Bairro MOOCA em SÃO PAULO?
#Passo anterior usando .isin
display(combustiveis_df.loc[(combustiveis_df['Bairro'] == 'MOOCA') & 
                            (combustiveis_df['Municipio'] == 'SAO PAULO') & 
                            (combustiveis_df['Produto'].isin(["GASOLINA", "GASOLINA ADITIVADA"])), 
                            ['Valor de Venda']].mean())

Valor de Venda    6.575596
dtype: float64

In [98]:
# Como mostrar média de valor de venda POR COMBUSTÍVEL Brasil todo?
# Round para menos casa decimal. 
media_por_combustivel_df = simples_df[['Produto', 'Valor de Venda',]].groupby(by='Produto').sum().round(2)
display(media_por_combustivel_df)

                    Valor de Venda
Produto
DIESEL                        4.07
DIESEL S10                    4.10
ETANOL                        4.00
GASOLINA                      5.26
GASOLINA ADITIVADA            5.30
GNV                           2.85

In [89]:
#Quero adicionar uma coluna de valor booleano no combustiveis_df
# chamada "Ativo" que, por padrão, vai ser True para 
# TODAS as linhas
combustiveis_df['Ativo'] = True
print(combustiveis_df.info())
display(combustiveis_df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168409 entries, 0 to 168408
Data columns (total 17 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Regiao - Sigla     168409 non-null  object
 1   Estado - Sigla     168409 non-null  object
 2   Municipio          168409 non-null  object
 3   Revenda            168409 non-null  object
 4   CNPJ da Revenda    168409 non-null  object
 5   Nome da Rua        168409 non-null  object
 6   Numero Rua         168353 non-null  object
 7   Complemento        35057 non-null   object
 8   Bairro             168043 non-null  object
 9   Cep                168409 non-null  object
 10  Produto            168409 non-null  object
 11  Data da Coleta     168409 non-null  datetime64[ns]
 12  Valor de Venda     168409 non-null  float64
 13  Valor de Compra    0 non-null       float64
 14  Unidade de Medida  168409 non-null  object
 15  Bandeira           168409 non-null  object
 16  Ativo              168409 non-null  bool
dtypes: bool(1), datetime64[ns](1), float64(2), object(13)
memory usage: 20.7+ MB
None

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira,Ativo
0,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA,2021-11-01,6.799,NaN,R$ / litro,VIBRA ENERGIA,True
1,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,ETANOL,2021-11-01,5.299,NaN,R$ / litro,VIBRA ENERGIA,True
2,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL,2021-11-01,5.549,NaN,R$ / litro,VIBRA ENERGIA,True
3,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA ADITIVADA,2021-11-01,6.899,NaN,R$ / litro,VIBRA ENERGIA,True
4,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL S10,2021-11-01,5.649,NaN,R$ / litro,VIBRA ENERGIA,True

In [104]:
# Exportar para Excel o dataframe com etanol em São Paulo....
etanol_saopaulo_df.to_excel('Etanol São Paulo.xlsx', sheet_name='Etanol São Paulo', index= False )

In [106]:
etanol_saopaulo_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1336 entries, 145884 to 11605
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Revenda         1336 non-null   object
 1   Municipio       1336 non-null   object
 2   Valor de Venda  1336 non-null   float64
 3   Produto         1336 non-null   object
dtypes: float64(1), object(3)
memory usage: 52.2+ KB